In [1]:
import numpy as np

In [2]:
a = np.random.rand(3,2)

In [3]:
print(a)

[[ 0.05031014  0.76650273]
 [ 0.31072701  0.96342162]
 [ 0.448379    0.6438668 ]]


In [4]:
a.shape

(3, 2)

In [7]:
b = np.random.rand(3,2)

In [8]:
print(b)

[[ 0.07479943  0.84573054]
 [ 0.54110998  0.50184404]
 [ 0.69283324  0.53769492]]


In [11]:
b = np.random.randn(3,2)

In [12]:
print(b)

[[ 1.11222443  0.93296963]
 [-1.80560769  0.47998227]
 [-1.64219758 -0.74409486]]


In [13]:
type(a.shape)

tuple

In [14]:
b = [3,2]

In [15]:
type(b)

list

In [18]:
a.shape[:]

(3, 2)

In [19]:
np.squeeze(a.shape)

array([3, 2])

In [25]:
c = np.array(a.shape)

np.random.rand()

TypeError: 'tuple' object cannot be interpreted as an integer

In [24]:
np.random.rand(c)

TypeError: only integer scalar arrays can be converted to a scalar index